name: Publish Terraform Module

on:
  push:
    tags:
      - "v1.0.0"

jobs:
  publish:
    name: Publish Module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Validate Terraform
        run: terraform validate

      - name: Publish Module
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: |
          curl \
            --header "Authorization: Bearer $TF_API_TOKEN" \
            --request POST \
            --data '{"data":{"type":"modules","attributes":{"vcs-repo":{"identifier":"Pradee030/Terraform-modules","display-identifier":"Pradee030/Terraform-modules"}}}}' \
            https://app.terraform.io/api/v2/organizations/Pradee030/registry-modules
